---
Prompt: "Please enter the name of the location only. Other details will be provided. Example 'Hawkins' will become 'Location - Hawkins':"
Mappings:
  Story:
    fields:
      project:
        key: STN
      issuetype:
        name: Story
      summary: ""
      reporter:
        name: "nancy.paulin@gameloft.com"
      components:
        - name: TEAM - Environment + VFX
  Task:
    fields:
      project:
        key: STN
      issuetype:
        name: Task
      summary: ""
      customfield_19581: "{parentKey}"
      reporter:
        name: "nancy.paulin@gameloft.com"
      components:
        - name: TEAM - Environment + VFX
    update:
      issuelinks:
        - add:
            type:
              name: Parent-Child
              inward: is parent of
              outward: is child of
            inwardIssue:
              key: "{parentKey}"
Structure:
  - type: Story
    step: "prompt"
    summary: "{location} {variation:(Int), (Ext)}"
    customfield_19673:
      value: "L1"
    items:
      - type: Task
        summary: "[L1][{query['[0].summary']}] Model"
      - type: Task
        summary: "[L2][{query['[0].summary']}] Prop Assets"
      - type: Task
        summary: "[L1][{query['[0].summary']}] Level Art"
      - type: Task
        summary: "[L1][{query['[0].summary']}] VFX"
      - type: Task
        summary: "[L1][{query['[0].summary']}] Lighting"
      - type: Task
        summary: "[L1][{query['[0].summary']}] Collision Pass"
