---
Prompt: "Please enter the name of the location only. Other details will be provided. Example 'Hawkins' will become 'Location - Hawkins':"
Mappings:
  Epic:
    fields:
      project:
        key: STN
      issuetype:
        name: Epic
      summary: "{feature}"
      customfield_10672: "{feature}"
      reporter:
        name: "{reporter}"
      components:
        - name: POD - Environment Art
  Story:
    fields:
      project:
        key: STN
      issuetype:
        name: Story
      summary: ""
      reporter:
        name: "{reporter}"
      components:
        - name: POD - Environment Art
      customfield_10671: "{parentKey}"
    update:
      issuelinks:
        - add:
            type:
              name: Parent-Child
              inward: is parent of
              outward: is child of
            inwardIssue:
              key: "{parentKey}"
  Task:
    fields:
      project:
        key: STN
      issuetype:
        name: Task
      summary: ""
      customfield_19581: "{parentKey}"
      reporter:
        name: "{reporter}"
      components:
        - name: POD - Environment Art
    update:
      issuelinks:
        - add:
            type:
              name: Parent-Child
              inward: is parent of
              outward: is child of
            inwardIssue:
              key: "{parentKey}"
Structure:
  - type: Epic
    summary: "{feature}"
    items:
      - type: Story
        summary: "[Q0][{feature}]"
        customfield_19673:
          value: "Q0"
        items:
          - type: Task
            summary: "[Q0][{feature}] Research"
            components:
              - name: POD - Narrative
              - name: POD - Environment Art
          - type: Task
            summary: "[Q0][{feature}] Concept Art"
            components:
              - name: POD - Narrative
              - name: POD - Environment Art
          - type: Task
            summary: "[Q0][{feature}] Props List"
            components:
              - name: POD - Narrative
              - name: POD - Environment Art
      - type: Story
        summary: "[Q1][{feature}]"
        customfield_19673:
          value: "Q1"
        items:
          - type: Task
            summary: "[Q1][{feature}] Whitebox"
      - type: Story
        summary: "[Q2][{feature}]"
        customfield_19673:
          value: "Q2"
        items:
          - type: Task
            summary: "[Q2][{feature}] Structure"
          - type: Task
            summary: "[Q2][{feature}] Props"
          - type: Task
            summary: "[Q2][{feature}] Level Art"
          - type: Task
            summary: "[Q2][{feature}] VFX"
          - type: Task
            summary: "[Q2][{feature}] Lighting"
    